include ../Makefile.tests_common

FEATURES_OPTIONAL += periph_rtc
DISABLE_MODULE += periph_init_rtc
FEATURES_OPTIONAL += periph_gpio_irq
USEMODULE += xtimer
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
